
CREATE DATABASE firtsExample;
USE  firtsExample;

CREATE TABLE PERIODICOS(
	ID int not null auto_increment PRIMARY KEY,
	ISS INT NOT NULL,
    NOME VARCHAR (120),
    ID_EDITORA int not null
);

DROP TABLE EDITORA;

CREATE TABLE EDITORA(
	ID int not null auto_increment PRIMARY KEY,
    NOME_EDITORA VARCHAR(120) UNIQUE,
    PAIS VARCHAR(10)
);

ALTER TABLE PERIODICOS ADD CONSTRAINT fk_editora_periodico FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA(ID);

INSERT INTO EDITORA( NOME_EDITORA,PAIS ) VALUES ('IEEE', 'EUA');
INSERT INTO EDITORA( NOME_EDITORA,PAIS ) VALUES ('DATASCIENCEMAGAZINE', 'EUA');
INSERT INTO EDITORA( NOME_EDITORA,PAIS ) VALUES ('IEE_EU', 'EU');

INSERT INTO PERIODICOS(NOME, ISS, ID_EDITORA) VALUES ('SPECIAL ISSUES', '111100000', '1');
INSERT INTO PERIODICOS(NOME, ISS, ID_EDITORA) VALUES ('EXEMPLO 2', '12345678', '3');
INSERT INTO PERIODICOS(NOME, ISS, ID_EDITORA) VALUES ('EXEMPLO 3', '12345678', '4');

SELECT * FROM  EDITORA;
SELECT * FROM PERIODICOS;



show tables;